[package]
name = "voicevox_core_ruby_api"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
easy-ext = "1.0.1"
magnus = { version = "0.4" }
voicevox_core.workspace = true
